app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/', 'UserAuthController@index');
Route::get('register', 'WelcomeController@register');
Route::get('signin', ['as' => 'user.signin.index', 'uses' => 'UserAuthController@index']);
Route::post('signin', ['as' => 'user.signin.post', 'uses' => 'UserAuthController@signingin']);
Route::get('signout', ['as' => 'user.signout', 'uses' => 'UserAuthController@signingout']);

		
	/**
	*  Routes for master period
	*/
	Route::resource('period', 'PeriodController', ['except' => ['destroy','show']]);
	Route::get('period/{id}/delete', ['as' => 'period.delete', 'uses' => 'PeriodController@destroy']);

app/Http/Controllers/PeriodController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\PeriodFormRequest;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Repositories\PeriodRepository;

class PeriodController extends Controller
{
    /**
     * @var PeriodRepository
     */
    protected $periodRepository;

    /**
     * @var Request
     */
    protected $httpRequest;

    /**
     * PeriodController constructor.
     *
     * @param PeriodRepository $periodRepository
     * @param Request $httpRequest
     */
    public function __construct(
        PeriodRepository $periodRepository,
        Request $httpRequest
    )
    {
        $this->periodRepository = $periodRepository;
        $this->httpRequest = $httpRequest;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->periodRepository->all();
        return view('backend.period.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.period.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request|PeriodFormRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(PeriodFormRequest $request)
    {
        if($this->periodRepository->store($request->except('_token'))) {
            //flash()->success('Data has been saved successfully');
            return redirect()->route('period.index');
        }
        $this->httpRequest->flashExcept(['_token']);
        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->periodRepository->findById($id);
        return view('backend.period.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request|PeriodFormRequest $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(PeriodFormRequest $request, $id)
    {
        if($this->periodRepository->update($id, $request->except(['_token', '_method']))) {
            //flash()->success('Data has been updated successfully');
            return redirect()->route('period.index');
        }
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->periodRepository->destroy($id);
        //flash()->success('Data has been deleted');
        return redirect()->route('period.index');
    }
}

resources/views/backend/period/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

    <!-- Bootstrap 3.3.4 -->
    <link href="{{ asset('assets/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.5/css/bootstrap-select.min.css">
    <!-- Ionicons -->
    <!-- <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" /> -->
    <link href="{{ asset('assets/plugins/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset('assets/dist/css/AdminLTE.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link href="{{ asset('assets/dist/css/skins/skin-blue.min.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">


    </head>
    <body>
          <h1>Master Period</h1>
    <form class="form-horizontal" action="{{ route('period.store') }}" method="post" accept-charset="utf-8" id="period_id" enctype="multipart/form-data">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">          
        <div class="form-group">
        <label for="nip" class="col-sm-3 control-label">Dari tanggal</label>
          <div class="col-sm-3">
              {!! Form::selectMonth('month_from', old('month_from'),['class'=>'selectpicker form-control','data-live-search' => 'false', 'autocomplete' => 'off']) !!}
          </div>
          <div class="col-sm-2">
              {!! Form::selectRange('year_from', 1990, 2050, old('year_from'), ['class'=>'selectpicker form-control','data-live-search' => 'false', 'autocomplete' => 'off']) !!}
          </div>
        </div>
        <br><br><br>
        <div class="form-group">
        <label for="nip" class="col-sm-3 control-label">Sampai tanggal</label>
          <div class="col-sm-3">
              {!! Form::selectMonth('month_to', old('month_to'),['class'=>'selectpicker form-control','data-live-search' => 'false', 'autocomplete' => 'off']) !!}
          </div>
          <div class="col-sm-2">
              {!! Form::selectRange('year_to', 1990, 2050, old('year_to'), ['class'=>'selectpicker form-control','data-live-search' => 'false', 'autocomplete' => 'off']) !!}
          </div>
        </div>    
        <br><br><br>
         <div class="form-group">
          <label for="nip" class="col-sm-3 control-label">Tipe</label>
          <div class="col-sm-3">
              {!! Form::select('status', ['1'=>'Aktif','0'=>'Tidak Aktif'], (old('status') == '1') ? old('1') : '1', ['class'=>'selectpicker form-control', 'id' => 'status', 'autocomplete' => 'off'])!!}
          </div>
        </div>
        </div>     
        <div class="box-footer col-md-offset-3">
        <button type="submit" class="btn btn-primary">Simpan</button>&nbsp;
        <a href="{{ route('period.index') }}" class="btn btn-warning">Kembali</a>
      </div>
    </form>         
    </body>
        <!-- jQuery 2.1.4 -->
    <script src="{{ asset('assets/plugins/jQuery/jQuery-2.1.4.min.js') }}"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{{ asset('assets/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/bootstrap/js/bootstrap-select.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/select2/js/select2.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('assets/dist/js/app.min.js') }}" type="text/javascript"></script> 
    <script>
      $('.selectpicker').selectpicker();
      $('.select2').select2({
        placeholder: "Pilih",
        allowClear: true
      });
    </script>
</html>

resources/views/backend/period/edit.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

    <!-- Bootstrap 3.3.4 -->
    <link href="{{ asset('assets/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.5/css/bootstrap-select.min.css">
    <!-- Ionicons -->
    <!-- <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" /> -->
    <link href="{{ asset('assets/plugins/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset('assets/dist/css/AdminLTE.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link href="{{ asset('assets/dist/css/skins/skin-blue.min.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">


    </head>
    <body>
          <h1>Master Period</h1>
        

    <form class="form-horizontal" action="{{ route('period.update', ['id'=>$data['period_id']]) }}" method="post" accept-charset="utf-8" id="period" enctype="multipart/form-data">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <input type="hidden" name="_method" value="put"> 
        <div class="form-group">
        <label for="nip" class="col-sm-3 control-label">Dari tanggal</label>
          <div class="col-sm-3">
              {!! Form::selectMonth('month_from', getPartialDate($data['period_from_date'], 'month'),['class'=>'selectpicker form-control','data-live-search' => 'false', 'autocomplete' => 'off']) !!}
          </div>
          <div class="col-sm-2">
              {!! Form::selectRange('year_from', 1990, 2050, getPartialDate($data['period_from_date'], 'year'), ['class'=>'selectpicker form-control','data-live-search' => 'false', 'autocomplete' => 'off']) !!}
          </div>
        </div>
        <br><br><br>
        <div class="form-group">
        <label for="nip" class="col-sm-3 control-label">Sampai tanggal</label>
          <div class="col-sm-3">
              {!! Form::selectMonth('month_to', getPartialDate($data['period_to_date'], 'month'),['class'=>'selectpicker form-control','data-live-search' => 'false', 'autocomplete' => 'off']) !!}
          </div>
          <div class="col-sm-2">
              {!! Form::selectRange('year_to', 1990, 2050, getPartialDate($data['period_to_date'], 'year'), ['class'=>'selectpicker form-control','data-live-search' => 'false', 'autocomplete' => 'off']) !!}
          </div>
        </div>    
        <br><br><br>
         <div class="form-group">
          <label for="nip" class="col-sm-3 control-label">Tipe</label>
          <div class="col-sm-3">
              {!! Form::select('status', ['1'=>'Aktif','0'=>'Tidak Aktif'], $data['period_status'], ['class'=>'selectpicker form-control', 'id' => $data['period_status'], 'autocomplete' => 'off'])!!}
          </div>
        </div>
        </div>     
        <div class="box-footer col-md-offset-3">
        <button type="submit" class="btn btn-primary">Simpan</button>&nbsp;
        <a href="{{ route('period.index') }}" class="btn btn-warning">Kembali</a>
      </div>
    </form>         
    </body>
        <!-- jQuery 2.1.4 -->
    <script src="{{ asset('assets/plugins/jQuery/jQuery-2.1.4.min.js') }}"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{{ asset('assets/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/bootstrap/js/bootstrap-select.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/select2/js/select2.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('assets/dist/js/app.min.js') }}" type="text/javascript"></script> 
    <script>
      $('.selectpicker').selectpicker();
      $('.select2').select2({
        placeholder: "Pilih",
        allowClear: true
      });
    </script>
</html>

resources/views/backend/period/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

    </head>
    <body>
          <h1>Master Period</h1>
            <div class="box-header with-border">
              <a href="{{ route('period.create') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Tambah Periode</a>
            </div><!-- /.box-header -->

                             <div class="table-responsive">
                    <table class="table no-margin table-condensed table-bordered table-hover table-striped">
                        <thead>
                            <tr class="bg-info">
                              <th class="col-md-2 text-center">From</th>
                              <th class="col-md-2 text-center">To</th>
                              <th class="col-md-1 text-center">Status</th>
                              <th class="col-md-2 text-center">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                        @forelse($data as $period)
                            <tr>
                                <td>{{ $period['period_from_date'] }}</td>
                                <td>{{ $period['period_to_date'] }}</td>
                                <td>{{ ($period['period_status'] == '1') ? 'Aktif' : "Tidak Aktif" }}</td>
                                <td class="text-center">
                                  <a href="{{ route('period.edit', ['id' => $period['period_id']]) }}" class="btn btn-xs btn-warning"><i class="fa fa-edit"></i>Edit</a>
                                  <a href="{{ route('period.delete', ['id' => $period['period_id']]) }}" class="btn btn-xs btn-danger" onclick="return confirm('Hapus data?'); "><i class="fa fa-trash"></i>Hapus</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="9">Tidak ada data</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table><br>
                 </div>


    </body>
</html>